-- 管理员
CREATE TABLE __PREFIX__administrator(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `priority` BIGINT UNSIGNED NOT NULL DEFAULT 7,
    `name` VARCHAR(31) NOT NULL,
    `account` VARCHAR(31) NOT NULL UNIQUE,
    `password` BINARY(16) NOT NULL,
    `signdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `logintime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 文章
CREATE TABLE __PREFIX__archive(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(127) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `status` ENUM("private", "public", "obsolete") NOT NULL DEFAULT "private",
    `createdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modifytime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 变量
CREATE TABLE __PREFIX__variant(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(63) NOT NULL UNIQUE,
    `value` VARCHAR(127) NOT NULL,
    `modifytime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- 关键字
CREATE TABLE __PREFIX__keyword(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `value` VARCHAR(63) NOT NULL,
    PRIMARY KEY (id)
);

-- 归类
CREATE TABLE __PREFIX__category(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `keywordid` BIGINT UNSIGNED NOT NULL,
    `archiveid` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);

-- 版权
CREATE TABLE __PREFIX__copyright(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `authorid` BIGINT UNSIGNED NOT NULL,
    `archiveid` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);
