--
DROP TABLE IF EXISTS __PREFIX__administrator;
DROP TABLE IF EXISTS __PREFIX__archive;
DROP TABLE IF EXISTS __PREFIX__keyword;
DROP TABLE IF EXISTS __PREFIX__category;
DROP TABLE IF EXISTS __PREFIX__copyright;