-- 管理员
CREATE TABLE __PREFIX__administrator(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项 ID',
    `account` VARCHAR(31) NOT NULL UNIQUE COMMENT '账户',
    `password` BINARY(32) NOT NULL COMMENT '密码',
    `nickname` VARCHAR(63) NOT NULL COMMENT '昵称',
    `signdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册日期',
    `logintime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登入日期',
    PRIMARY KEY (`id`)
) COMMENT '管理员';

-- 权限
CREATE TABLE __PREFIX__permission(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项 ID',
    `ownerid` BIGINT UNSIGNED NOT NULL COMMENT '主体标识',
    `token` BIGINT UNSIGNED NOT NULL COMMENT '权限标识',
    `permitdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权日期',
    PRIMARY KEY (`id`)
) COMMENT '权限';
